execute predict-genome-wide correctly

diff --git a/constraint-tools b/constraint-tools
--- a/constraint-tools
+++ b/constraint-tools
@@ -30,17 +30,22 @@ shift
 args="${@}"
 info "Tool arguments: " "${args}"
 
-if [[ ${tool} == "train-germline-model" ]]; then 
-  PATH="${CONSTRAINT_TOOLS}/train/germline-model:$PATH" 
-  train-map-reduce ${args}
-elif [[ ${tool} == "browse-germline-model" ]]; then 
-  PYTHONPATH="${CONSTRAINT_TOOLS}/predict-constraint/germline-model:${PYTHONPATH}"
-  PATH="${CONSTRAINT_TOOLS}/flask-app/germline-model:${PATH}"
-  flask-app ${args} 
-elif [[ ${tool} == "predict-germline-model" ]]; then 
-  PYTHONPATH="${CONSTRAINT_TOOLS}/predict-constraint/germline-model:${PYTHONPATH}"
-  predict-genome-wide ${args} 
-else
-  error "invalid tool: " "${tool}"
-  exit 1
-fi 
+case "${tool}" in 
+  train-germline-model ) 
+    PATH="${CONSTRAINT_TOOLS}/train/germline-model:$PATH" 
+    train-map-reduce ${args}
+    ;;
+  browse-germline-model ) 
+    PYTHONPATH="${CONSTRAINT_TOOLS}/predict-constraint/germline-model:${PYTHONPATH}"
+    PATH="${CONSTRAINT_TOOLS}/flask-app/germline-model:${PATH}"
+    flask-app ${args} 
+    ;;
+  predict-germline-model ) 
+    PATH="${CONSTRAINT_TOOLS}/predict-constraint/germline-model:${PATH}"
+    predict-genome-wide ${args} 
+    ;; 
+  * )
+    error "invalid tool: " "${tool}"
+    exit 1
+    ;; 
+esac 
