make a tsv file of variants for chromosome 1 (2)

diff --git a/download-process-data/gnomad/v3/variants/vcf-to-tsv-chromosome b/download-process-data/gnomad/v3/variants/vcf-to-tsv-chromosome
--- a/download-process-data/gnomad/v3/variants/vcf-to-tsv-chromosome
+++ b/download-process-data/gnomad/v3/variants/vcf-to-tsv-chromosome
@@ -21,7 +21,7 @@ set -o nounset
 
 #######################################
 
-info "extract vep labels from vcf for this particular chromosome ..."
+info "extract vep labels from vcf for ${chromosome} ..."
 
 variants_directory="${CONSTRAINT_TOOLS_DATA}/gnomad/v3/variants" 
 variants="${variants_directory}/gnomad_v3_${chromosome}"
@@ -37,7 +37,7 @@ bcftools view -h ${variants}.vcf.gz \
 
 #######################################
 
-info "get intervals for this specific chromosome ..."
+info "get intervals for ${chromosome} ..."
 
 intervals="${CONSTRAINT_TOOLS_DATA}/map-reduce-intervals/intervals.bed"
 intervals_on_chromosome="${CONSTRAINT_TOOLS_DATA}/map-reduce-intervals/intervals.${chromosome}.bed"
@@ -55,56 +55,69 @@ fi
 
 #######################################
 
-# TODO: delete 
-number_of_jobs="10"
+# info "Submitting slurm job array for ${chromosome} with ${number_of_jobs} jobs (tasks) and ${number_of_intervals_per_job} intervals per job..."
 
-info "Submitting slurm job array with ${number_of_jobs} jobs (tasks) and ${number_of_intervals_per_job} intervals per job..."
+# # each slurm task will store its output files in this temporary directory: 
+# tmpdir=$(mktemp --tmpdir=${variants_directory} --directory)
+# clean_up () {
+#   local exit_code="$1"
+#   if [[ "${exit_code}" == "0" ]]; then 
+#     info "Deleting tmp directory for ${chromosome}..."
+#     rm --recursive --force "${tmpdir}"
+#   else 
+#     info "Received exit code ${exit_code}.."
+#     info "Not deleting tmp directory for ${chromosome}..."
+#   fi 
+# }
+# # http://redsymbol.net/articles/bash-exit-traps/
+# # https://medium.com/@dirk.avery/the-bash-trap-trap-ce6083f36700
+# trap 'clean_up $?' EXIT
 
-# each slurm task will store its output files in this temporary directory: 
-tmpdir=$(mktemp --tmpdir=${variants_directory} --directory)
-clean_up () {
-  rm --recursive --force "${tmpdir}"
-}
-# TODO: uncomment once debugging is complete:  
-# trap clean_up EXIT
+# success_signature="TSV FILE READY TO MERGE"
 
-success_signature="TSV FILE READY TO MERGE"
-
-# sbatch man-page: 
-# A maximum number of simultaneously running tasks from the job array may be
-# specified using a "%" separator.  
-# For example "--array=0-15%4" will limit the number of simultaneously running
-# tasks from this job array to 4.
-# We "wait" for two reasons: 
-#   1. to ensure that all the jobs/tasks are finished before merging their results
-#   2. because the number of jobs per chromosome is already at the allowable limit for job submissions on slurm
-sbatch \
-  --wait \
-  --array [1-${number_of_jobs}]%250 \
-  --job-name "vcf-to-tsv-${chromosome}" \
-  --output ${tmpdir}/gnomad_v3_${chromosome}.vcf-to-tsv.job-%A.task-%a.log \
-  vcf-to-tsv-intervals \
-    --vcf ${variants}.vcf.gz \
-    --vep-keys ${vep_keys} \
-    --intervals-on-chromosome ${intervals_on_chromosome} \
-    --number-of-intervals-per-job ${number_of_intervals_per_job} \
-    --tmpdir ${tmpdir} \
-    --success-signature "${success_signature}"
+# # sbatch man-page: 
+# # A maximum number of simultaneously running tasks from the job array may be
+# # specified using a "%" separator.  
+# # For example "--array=0-15%4" will limit the number of simultaneously running
+# # tasks from this job array to 4.
+# # We "wait" for two reasons: 
+# #   1. to ensure that all the jobs/tasks are finished before merging their results
+# #   2. because the number of jobs per chromosome is already at the allowable limit for job submissions on slurm
+# sbatch \
+#   --wait \
+#   --array [1-${number_of_jobs}]%250 \
+#   --job-name "vcf-to-tsv-${chromosome}" \
+#   --output ${tmpdir}/gnomad_v3_${chromosome}.vcf-to-tsv.job-%A.task-%a.log \
+#   vcf-to-tsv-intervals \
+#     --vcf ${variants}.vcf.gz \
+#     --vep-keys ${vep_keys} \
+#     --intervals-on-chromosome ${intervals_on_chromosome} \
+#     --number-of-intervals-per-job ${number_of_intervals_per_job} \
+#     --tmpdir ${tmpdir} \
+#     --success-signature "${success_signature}"
 
 #######################################
 
-number_of_successful_jobs="0"
-for log_file in ${tmpdir}/*.log; do 
-  last_line="$(tail --lines=1 ${log_file})"
-  if [[ "${last_line}" == "${success_signature}" ]]; then
-    ((number_of_successful_jobs = number_of_successful_jobs + 1))
-  fi
-done 
-
-if [[ ${number_of_successful_jobs} -ne ${number_of_jobs} ]]; then
-	info "Some jobs failed... Did not merge..." 
-	exit 1
+set +o errexit
+number_of_log_files=$(ls ${tmpdir}/*.log | wc -l)
+set -o errexit
+if [[ ${number_of_log_files} != ${number_of_jobs} ]]; then 
+  error "only ${number_of_log_files}/${number_of_jobs} jobs completed successfully"
+  error "did not merge..."
+  exit 1 
 fi 
+
+for log_file in ${tmpdir}/*.log; do 
+  set +o errexit
+  number_of_successfully_processed_intervals_per_job=$(grep --count "^${success_signature}" ${log_file}) 
+  set -o errexit
+  if [[ ${number_of_successfully_processed_intervals_per_job} != "2" ]]; then 
+    error "only ${number_of_successfully_processed_intervals_per_job}/2 intervals were completed successfully"
+    error "log file: ${log_file}"
+    error "did not merge..."
+    exit 1
+  fi 
+done 
 
 info "All jobs to convert ${chromosome} variants from vcf to tsv format were successful..."
 
